### ISSUE TITLE
showing error when importing Mysql data

### ISSUE THREAD

**Issue by harshkulkar** [prettyblueberry/car-auction-react#2]
![1](https://github.com/prettyblueberry/car-auction-react/assets/140954526/e860ac13-aaf0-4200-89fa-8a82738aaf85)
![2](https://github.com/prettyblueberry/car-auction-react/assets/140954526/680e130b-8bf4-49ca-a475-3feb880160dc)

**Comment by prettyblueberry** [comment]
Hi @harshkulkar, 

My project is frontend-only and it doesn't have any backend, so the MySQL issue is out of the project. 

Could you explain the issue in more detail, please?

Thank you.

**Comment by harshkulkar** [comment]
Hello,
I just updated my issue please see to it again
I have provided pictures.

**Comment by prettyblueberry** [comment]
Dear @harshkulkar 

I'm sorry to say same word again.

**My project is frontend-only and it doesn't have any backend, so the MySQL issue is out of the project.** 

- Your issue is from your backend. But my project doesn't handle have any backend and database. My project is focusing on frontend and MUI only to show a landing page (frontend) for a real-time car auction.

- The MySQL dump is not my work. I didn't provide any MySQL dump file or table structures for this project, so I can't help you. You need to contact a right provider of the MySQL dump file.

**I mean your issue is not an issue from this repository.**

I believe it will help you.

**Comment by harshkulkar** [comment]
Thank you for your response.
I will end my issue
